### PR TITLE
Add friendly_id

### PR DESCRIPTION
**Pull request by marinalimeira**

### CODE REVIEW

**Comment by gmmcal** [comment]
@marinalimeira so far is awesome! Just some small tweaks.

* Can you also add the slug on event?
* You don't need to add ```use: [:slugged, :finders]``` on the model if you enable ```config.use :finders``` and ```config.use :slugged```. Since this will be a standard on this app, please use it. This will make the model with less information.
* You can remove the CreateFriendlyIdSlugs migration. This is used for avoiding 404 when slug changes, but this won't be a problem for us. http://norman.github.io/friendly_id/file.Guide.html#History__Avoiding_404_s_When_Slugs_Change
* on AddSlugToParticipants migration, you can set the unique key on a single line ```add_column :participants, :slug, :string, unique: true```

Thanks

**Comment by marinalimeira** [comment]
How am I supposed to enable this

**Comment by gmmcal** [comment]
You can change it on config/initializers/friendly_id.rb

**Comment by marinalimeira** [comment]
Done :smile:

**Comment by juarezpaf** [comment]
:rocket:

**Pull request merged**
